### ISSUE TITLE
quran text is inconsistent please be very aware because this should not have any mistakes

### ISSUE THREAD

**Issue by yousif-hag-ahmed** [risan/quran-json#7]
quran text is inconsistent please be very aware because this should not have any mistakes 
for example 
![Correction](https://user-images.githubusercontent.com/69925471/109892164-6a75bf80-7c58-11eb-9a71-f76d5a8cc96b.PNG)

should be 

![correct](https://user-images.githubusercontent.com/69925471/109892834-aad53d80-7c58-11eb-854d-dc27c76a9613.PNG)

please be aware ,thank you for the effort

_Originally posted by @yousif-hag-ahmed in https://github.com/risan/quran-json/issues/6#issuecomment-790192998_

**Comment by risan** [comment]
Hi, thank you for your concern. Close this issue, see #6
